### ISSUE TITLE
Breadcrumbs: Overflow control?

### ISSUE THREAD

**Issue by getflourish** [Frontify/fondue#643]
This is a feature request, that you might already have planned. But I’ll report it anyway: it would be nice to control the overflow of the breadcrumbs. Currently it wraps on a multiple lines which is often a good solution. But in the future these would be useful and make it a more flexible component for many use cases:

- truncate the middle, so that both the start and end of a path are visible 
- truncate the end by showing overflowing items in a dropdown

<img width="309" alt="image" src="https://user-images.githubusercontent.com/183989/156329938-c0c6db4e-2cf0-4bde-b5d2-45fd2d7d4302.png">

**Comment by getflourish** [comment]
Related: 

When the active item wraps, the spacing between breadcrumbs and the active items gets more dense.

Default:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/183989/179195694-6ea95f6d-acdf-4414-8888-e2fca84db3ef.png">

Dense spacing with overflow:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/183989/179195641-122d31a6-058e-48b6-a798-f06c3e9e9a18.png">

**Comment by imoutaharik** [comment]
The second issue reported has been fixed.

I created a task to address the truncate feature request. We actually have a design for this and an overflow menu will be added soon.

**Comment by jonasbuechel** [comment]
There's a solution design for truncating overflowing breadcrumbs here:
https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue---Components?node-id=11988%3A437657

**Comment by ryancarville** [comment]
@jonasbuechel @getflourish This report is very old.  By chance has this been addressed already, but the issue was not closed?

**Comment by getflourish** [comment]
Still an issue. I just added some junk content to the component on Storybook:
<img width="479" alt="image" src="https://github.com/Frontify/fondue/assets/183989/d9565223-c9ed-47c4-9a30-518034f57cf7">

This is mainly an issue when the component is used in narrow contexts, e.g. sidebars or mobile

**Comment by ryancarville** [comment]
Thanks @getflourish!  Sorry I removed my previous comment as I just dove into the Figma and the component and quickly realised it is still open.  I am on it!

**Comment by ryancarville** [comment]
![Screenshot 2023-10-24 at 13 26 38](https://github.com/Frontify/fondue/assets/47146443/0b3e2085-4896-4fb4-927a-bff360101f6b)

Will this solution still satisfy your request?  Design was from a year ago so I am not sure.

**Comment by getflourish** [comment]
Looks good to me! Paired with text overflow of the individual items, this would allow the breadcrumbs to stay on a single row. But I think it’s worth keeping the old wrapping behavior as an option, too.

**Comment by ryancarville** [comment]
@getflourish if you like to and when you can [HERE](https://deploy-preview-1632--beta-fondue-components.netlify.app/?path=/docs/components-breadcrumbs--docs) is a preview of the logic for truncation.  Let me know if you see anything I am missing.

**Comment by ryancarville** [comment]
@getflourish do you have a opinion on what the maximum width of a `crumb` should be?  If we want to enforce `line wrapping` we need to set a `max-width`.
